<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = $this->getProducts();

        foreach ($products as $product) {
            $categoryId = DB::table('categories')->where('slug', $product['category_slug'])->value('id');
            $brandId    = DB::table('brands')->where('slug', $product['brand_slug'])->value('id');

            if (! $categoryId || ! $brandId) {
                continue;
            }

            $slug = Str::slug($product['name']);
            $base = $slug;
            $i    = 1;
            while (DB::table('products')->where('slug', $slug)->exists()) {
                $slug = $base . '-' . $i++;
            }

            DB::table('products')->insert([
                'name'              => $product['name'],
                'slug'              => $slug,
                'sku'               => $product['sku'],
                'thumbnail'         => $product['thumbnail'] ?? 'https://placehold.co/400x400/f3f4f6/374151?text=' . urlencode($product['name']),
                'images'            => json_encode($product['images'] ?? []),
                'price'             => $product['price'],
                'original_price'    => $product['original_price'] ?? null,
                'short_description' => $product['short_description'],
                'description'       => $product['description'],
                'is_new'            => $product['is_new'] ?? false,
                'is_featured'       => $product['is_featured'] ?? false,
                'in_stock'          => $product['in_stock'] ?? true,
                'stock_qty'         => $product['stock_qty'] ?? 10,
                'category_id'       => $categoryId,
                'brand_id'          => $brandId,
                'specs'             => isset($product['specs']) ? json_encode($product['specs']) : null,
                'tags'              => json_encode($product['tags'] ?? []),
                'rating'            => $product['rating'] ?? null,
                'review_count'      => $product['review_count'] ?? 0,
                'sales_count'       => $product['sales_count'] ?? 0,
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ]);
        }
    }

    /** @return array<int,array<string,mixed>> */
    private function getProducts(): array
    {
        return [
            // ─── BEST SELLERS (high sales_count) ────────────────────────────
            [
                'name'              => 'Rational SCC WE 6-1/1 Combi Oven',
                'sku'               => 'RAT-SCC-61',
                'category_slug'     => 'combi-ovens',
                'brand_slug'        => 'rational',
                'price'             => 28500.00,
                'original_price'    => 33000.00,
                'is_featured'       => true,
                'sales_count'       => 1240,
                'rating'            => 4.90,
                'review_count'      => 187,
                'short_description' => '6 x 1/1 GN combi oven with WiFi connectivity. Ideal for restaurants and hotels.',
                'description'       => 'The Rational SCC WE combi oven combines steam, convection and combination cooking in one unit. Features 6 × 1/1 GN capacity, WiFi-based ConnectedCooking, and Efficient CareControl automatic cleaning. Suitable for meat, fish, vegetables and bakery items.',
                'specs'             => ['Capacity' => '6 × 1/1 GN', 'Power Supply' => '400V / 3N~', 'Connected Load' => '10.5 kW', 'Dimensions (mm)' => '847 × 771 × 748', 'Weight' => '85 kg'],
                'tags'              => ['combi oven', 'rational', 'restaurant', 'hotel'],
            ],
            [
                'name'              => 'Hobart ECOMAX 504 Hood Dishwasher',
                'sku'               => 'HOB-ECO-504',
                'category_slug'     => 'commercial-dishwashers',
                'brand_slug'        => 'hobart',
                'price'             => 15200.00,
                'original_price'    => 18500.00,
                'is_featured'       => true,
                'sales_count'       => 980,
                'rating'            => 4.75,
                'review_count'      => 143,
                'short_description' => 'High-performance hood dishwasher, 540 racks/hour, heat recovery system.',
                'description'       => 'The Hobart ECOMAX 504 hood-type dishwasher delivers exceptional cleaning performance with up to 540 racks per hour. Features integrated heat recovery reducing energy consumption by up to 25%, dual-rinse system, and automatic soil-level detection.',
                'specs'             => ['Capacity' => '540 racks/hr', 'Wash Temp' => '60°C', 'Rinse Temp' => '85°C', 'Power' => '400V / 3N~', 'Tank Volume' => '25 L'],
                'tags'              => ['dishwasher', 'hobart', 'warewashing'],
            ],
            [
                'name'              => 'Hoshizaki IM-130NE-HC Ice Machine',
                'sku'               => 'HSK-IM130',
                'category_slug'     => 'ice-machines',
                'brand_slug'        => 'hoshizaki',
                'price'             => 8750.00,
                'original_price'    => 10200.00,
                'is_featured'       => true,
                'sales_count'       => 875,
                'rating'            => 4.80,
                'review_count'      => 132,
                'short_description' => '130 kg/24h crescent cube ice maker with 50 L storage bin. R-404A refrigerant.',
                'description'       => 'The Hoshizaki IM-130NE-HC produces clear, slow-melting crescent cubes at up to 130 kg per 24 hours. Stainless steel evaporator, anti-microbial EvaporatorGuard, and easy front-access cleaning. Suitable for bars, hotels, and restaurants.',
                'specs'             => ['Ice Production' => '130 kg / 24h', 'Storage Bin' => '50 L', 'Refrigerant' => 'R-404A', 'Dimensions (mm)' => '640 × 620 × 965', 'Weight' => '78 kg'],
                'tags'              => ['ice machine', 'hoshizaki', 'bar', 'hotel'],
            ],
            [
                'name'              => 'Robot Coupe R401 Food Processor',
                'sku'               => 'RC-R401',
                'category_slug'     => 'food-processors-cutters',
                'brand_slug'        => 'robot-coupe',
                'price'             => 4200.00,
                'original_price'    => 5000.00,
                'is_featured'       => true,
                'sales_count'       => 740,
                'rating'            => 4.85,
                'review_count'      => 98,
                'short_description' => '4.5 L food processor with two-speed motor. Includes stainless steel s-blade and disc.',
                'description'       => 'The Robot Coupe R401 is the professional kitchen workhorse. Equipped with a 2-speed 1.5 kW motor, 4.5 L stainless bowl, and an extensive range of discs and blades. Perfect for chopping, slicing, grating, and mixing.',
                'specs'             => ['Bowl Capacity' => '4.5 L', 'Motor' => '1.5 kW', 'Speeds' => '2 (350 / 1500 rpm)', 'Power Supply' => '230V / 50Hz', 'Weight' => '9.2 kg'],
                'tags'              => ['food processor', 'robot coupe', 'preparation'],
            ],
            [
                'name'              => 'Vitamix 5200 Commercial Blender',
                'sku'               => 'VTX-5200',
                'category_slug'     => 'commercial-blenders',
                'brand_slug'        => 'vitamix',
                'price'             => 2850.00,
                'original_price'    => 3400.00,
                'is_featured'       => false,
                'sales_count'       => 680,
                'rating'            => 4.90,
                'review_count'      => 215,
                'short_description' => 'Variable speed commercial blender. 2-peak HP motor, 1.4 L container.',
                'description'       => 'The Vitamix 5200 delivers consistent, commercial-grade blending performance. Its 2-peak HP motor and laser-cut stainless steel blades handle hot soups, frozen desserts, and smoothies effortlessly. Variable speed control with pulse feature.',
                'specs'             => ['Motor' => '2 HP peak', 'Container' => '1.4 L', 'Speed Settings' => '10 variable', 'Dimensions' => '18 × 18 × 46 cm', 'Weight' => '5.2 kg'],
                'tags'              => ['blender', 'vitamix', 'bar', 'restaurant'],
            ],
            [
                'name'              => 'Garland G60-6CS 6-Burner Gas Range',
                'sku'               => 'GAR-G60-6CS',
                'category_slug'     => 'commercial-gas-ranges',
                'brand_slug'        => 'garland',
                'price'             => 9800.00,
                'original_price'    => 13500.00,
                'is_featured'       => true,
                'sales_count'       => 590,
                'rating'            => 4.70,
                'review_count'      => 76,
                'short_description' => '6-burner commercial gas range with 26 L oven. Heavy-duty cast iron grates.',
                'description'       => 'The Garland G60-6CS is a heavy-duty 6-burner gas range designed for commercial kitchens. Features 33,000 BTU open burners, a 26 L oven with 25,000 BTU burner, cast-iron grates, and stainless steel construction throughout.',
                'specs'             => ['Burners' => '6 × 33,000 BTU', 'Oven Capacity' => '26 L', 'Oven Burner' => '25,000 BTU', 'Width' => '1524 mm', 'Weight' => '218 kg'],
                'tags'              => ['gas range', 'garland', 'restaurant', 'cooking'],
            ],
            [
                'name'              => 'True T-49 Reach-In Refrigerator',
                'sku'               => 'TRUE-T49',
                'category_slug'     => 'commercial-upright-refrigerators',
                'brand_slug'        => 'true-refrigeration',
                'price'             => 7200.00,
                'original_price'    => 8800.00,
                'is_featured'       => false,
                'sales_count'       => 540,
                'rating'            => 4.65,
                'review_count'      => 63,
                'short_description' => '2-door 49 cu. ft. reach-in refrigerator. LED interior, self-contained refrigeration.',
                'description'       => 'The True T-49 two-door reach-in refrigerator offers 49 cu. ft. of storage with LED lighting, self-contained refrigeration system, and CFC-free insulation. Stainless steel interior and exterior, with 4 adjustable PVC coated shelves per section.',
                'specs'             => ['Capacity' => '49 cu. ft.', 'Doors' => '2', 'Temperature Range' => '-1°C to +7°C', 'Refrigerant' => 'R-290', 'Width' => '1369 mm'],
                'tags'              => ['refrigerator', 'true', 'cold storage'],
            ],
            [
                'name'              => 'Cambro 18263CW Display Gastronorm Containers Set',
                'sku'               => 'CAM-18263CW',
                'category_slug'     => 'storage-containers',
                'brand_slug'        => 'cambro',
                'price'             => 380.00,
                'original_price'    => 480.00,
                'is_featured'       => false,
                'sales_count'       => 1650,
                'rating'            => 4.60,
                'review_count'      => 310,
                'short_description' => 'Set of 6 polycarbonate food storage containers with lids. 1/6 GN, clear.',
                'description'       => 'Cambro polycarbonate gastronorm containers are the industry standard for food storage, prep, and display. BPA-free, temperature range -40°C to +99°C, dishwasher safe. Set includes 6 containers with matching lids.',
                'specs'             => ['Size' => '1/6 GN', 'Material' => 'Polycarbonate', 'Temp Range' => '-40°C to +99°C', 'Set Contents' => '6 containers + 6 lids'],
                'tags'              => ['storage', 'cambro', 'gastronorm'],
            ],
            [
                'name'              => 'Vulcan V2SG-1 2-Burner Gas Hotplate',
                'sku'               => 'VUL-V2SG-1',
                'category_slug'     => 'commercial-gas-ranges',
                'brand_slug'        => 'vulcan',
                'price'             => 5200.00,
                'original_price'    => 7500.00,
                'is_featured'       => false,
                'sales_count'       => 460,
                'rating'            => 4.55,
                'review_count'      => 54,
                'short_description' => '2-burner gas hotplate, 30,000 BTU per burner. Stainless front and sides.',
                'description'       => 'The Vulcan V2SG-1 two-burner gas hotplate offers powerful 30,000 BTU open burners on a compact frame. Heavy cast iron grates, standing pilot ignition, and full stainless exterior. Ideal for supplementary cooking stations.',
                'specs'             => ['Burners' => '2 × 30,000 BTU', 'Width' => '610 mm', 'Gas Type' => 'Natural Gas / LPG', 'Weight' => '45 kg'],
                'tags'              => ['hotplate', 'vulcan', 'cooking'],
            ],
            [
                'name'              => 'Winterhalter PT-M Pass-Through Dishwasher',
                'sku'               => 'WTH-PTM',
                'category_slug'     => 'commercial-dishwashers',
                'brand_slug'        => 'winterhalter',
                'price'             => 32000.00,
                'original_price'    => 38000.00,
                'is_featured'       => true,
                'sales_count'       => 420,
                'rating'            => 4.95,
                'review_count'      => 89,
                'short_description' => 'Pass-through dishwasher with heat recovery. 720 racks/hr, touchscreen control.',
                'description'       => 'The Winterhalter PT-M delivers flawless results at 720 racks per hour. Advanced heat recovery system, intelligent dosing systems integration, and intuitive TouchControl. Built for high-volume hotel and catering operations.',
                'specs'             => ['Capacity' => '720 racks/hr', 'Wash Temp' => '55–65°C', 'Rinse Temp' => '82–90°C', 'Power' => '400V / 3N~', 'Heat Recovery' => 'Yes'],
                'tags'              => ['dishwasher', 'winterhalter', 'hotel'],
            ],

            // ─── NEW ARRIVALS (is_new = true) ────────────────────────────────
            [
                'name'              => 'Rational iCombi Pro 6-1/1 Combi Oven',
                'sku'               => 'RAT-ICPRO-61',
                'category_slug'     => 'combi-ovens',
                'brand_slug'        => 'rational',
                'price'             => 45000.00,
                'is_new'            => true,
                'is_featured'       => true,
                'sales_count'       => 85,
                'rating'            => 5.00,
                'review_count'      => 12,
                'short_description' => 'Next-generation iCombi Pro with iProductionManager. 12 intelligent cooking modes.',
                'description'       => 'The Rational iCombi Pro sets new standards in commercial cooking. Featuring iProductionManager for fully automatic multi-item cooking, iCookingSuite with 12 intelligent cooking modes, and automatic cleaning with iCareSystem. 6 × 1/1 GN capacity.',
                'specs'             => ['Capacity' => '6 × 1/1 GN', 'Cooking Modes' => '12', 'Power' => '400V / 3N~', 'Connected Load' => '11.0 kW', 'Width' => '847 mm'],
                'tags'              => ['combi oven', 'rational', 'new', 'restaurant'],
            ],
            [
                'name'              => 'La Marzocco Linea Classic S Espresso Machine',
                'sku'               => 'LM-LINEAS-2G',
                'category_slug'     => 'commercial-coffee-machines',
                'brand_slug'        => 'la-marzocco',
                'price'             => 22000.00,
                'is_new'            => true,
                'is_featured'       => true,
                'sales_count'       => 62,
                'rating'            => 4.95,
                'review_count'      => 28,
                'short_description' => '2-group commercial espresso machine. Dual boiler, Saturated groups, USB connectivity.',
                'description'       => 'The La Marzocco Linea Classic S brings iconic Italian espresso technology with modern connectivity. Dual boiler system, saturated groups for thermal stability, PID temperature control, and a USB port for software updates and the La Marzocco Home app.',
                'specs'             => ['Groups' => '2', 'Boiler System' => 'Dual boiler', 'Boiler Capacity' => '7 L + 2 × 0.4 L', 'Power' => '220–240V', 'Weight' => '42 kg'],
                'tags'              => ['espresso', 'coffee', 'la marzocco', 'new'],
            ],
            [
                'name'              => 'Hoshizaki DC-170 Display Chiller',
                'sku'               => 'HSK-DC170',
                'category_slug'     => 'display-chillers-showcase',
                'brand_slug'        => 'hoshizaki',
                'price'             => 12500.00,
                'is_new'            => true,
                'is_featured'       => false,
                'sales_count'       => 38,
                'rating'            => 4.70,
                'review_count'      => 9,
                'short_description' => '170 L upright display chiller with LED lighting. 0°C–+10°C. Curved glass door.',
                'description'       => 'The Hoshizaki DC-170 upright display chiller is ideal for showcasing beverages, desserts, and fresh produce. Curved glass door, white LED internal lighting, digital temperature control, and environmentally friendly R-290 refrigerant.',
                'specs'             => ['Capacity' => '170 L', 'Temp Range' => '0°C to +10°C', 'Refrigerant' => 'R-290', 'Lighting' => 'LED', 'Width' => '600 mm'],
                'tags'              => ['display chiller', 'hoshizaki', 'new'],
            ],
            [
                'name'              => 'Electrolux Professional Air-O-Steam Touchline 10-1/1',
                'sku'               => 'ELP-AOS-101',
                'category_slug'     => 'combi-ovens',
                'brand_slug'        => 'electrolux-professional',
                'price'             => 38500.00,
                'is_new'            => true,
                'is_featured'       => true,
                'sales_count'       => 44,
                'rating'            => 4.85,
                'review_count'      => 17,
                'short_description' => '10 × 1/1 GN combi oven with Touchline interface. SkyDoor opening system.',
                'description'       => 'The Electrolux Professional air-o-steam Touchline features the intuitive SkyDoor opening system, 7-inch touchscreen, automatic Automatic Cooking Control (ACC), and EcoDelta cooking for precise temperature management. 10 × 1/1 GN capacity.',
                'specs'             => ['Capacity' => '10 × 1/1 GN', 'Interface' => '7" Touchline', 'Door' => 'SkyDoor', 'Power' => '400V / 3N~', 'Connected Load' => '16.1 kW'],
                'tags'              => ['combi oven', 'electrolux', 'new'],
            ],
            [
                'name'              => 'Franke A600 FM Bean-to-Cup Coffee Machine',
                'sku'               => 'FRK-A600FM',
                'category_slug'     => 'commercial-coffee-machines',
                'brand_slug'        => 'franke-coffee-systems',
                'price'             => 18900.00,
                'is_new'            => true,
                'is_featured'       => false,
                'sales_count'       => 55,
                'rating'            => 4.80,
                'review_count'      => 21,
                'short_description' => 'Automatic bean-to-cup with milk system. 250 cups/day. 10-inch HD touchscreen.',
                'description'       => 'The Franke A600 FM delivers consistently excellent coffee at up to 250 cups per day. 10-inch HD touchscreen for simple operation, integrated FoamMaster milk system, 2 coffee bean hoppers, and automatic cleaning cycles.',
                'specs'             => ['Capacity' => '250 cups/day', 'Screen' => '10" HD touchscreen', 'Bean Hoppers' => '2', 'Power' => '230V / 50Hz', 'Weight' => '26 kg'],
                'tags'              => ['coffee machine', 'franke', 'bean to cup', 'new'],
            ],
            [
                'name'              => 'Atosa MGF8401GR Under-Counter Freezer',
                'sku'               => 'ATO-MGF8401',
                'category_slug'     => 'commercial-freezers',
                'brand_slug'        => 'atosa',
                'price'             => 4200.00,
                'is_new'            => true,
                'is_featured'       => false,
                'sales_count'       => 72,
                'rating'            => 4.55,
                'review_count'      => 18,
                'short_description' => '115 L under-counter freezer. -23°C to -13°C. 2 GN shelves included.',
                'description'       => 'The Atosa MGF8401GR under-counter freezer fits seamlessly under standard prep tables. 115 L capacity, digital temperature controller, auto-defrost, and 2 GN-compatible shelves. Ideal for prep kitchens and pastry sections.',
                'specs'             => ['Capacity' => '115 L', 'Temp Range' => '-23°C to -13°C', 'Defrost' => 'Auto', 'Refrigerant' => 'R-290', 'Width' => '700 mm'],
                'tags'              => ['freezer', 'atosa', 'under-counter', 'new'],
            ],

            // ─── TOP DEALS (discounted) ───────────────────────────────────────
            [
                'name'              => 'Alto-Shaam 750-TH/III Cook & Hold Oven',
                'sku'               => 'ALS-750TH',
                'category_slug'     => 'commercial-electric-ovens',
                'brand_slug'        => 'alto-shaam',
                'price'             => 7400.00,
                'original_price'    => 10800.00,
                'is_featured'       => false,
                'sales_count'       => 310,
                'rating'            => 4.75,
                'review_count'      => 56,
                'short_description' => 'Cook & Hold oven with Halo Heat technology. 12 × 1/1 GN. -31% AED saving.',
                'description'       => 'Alto-Shaam Halo Heat surrounds food with gentle, even radiant heat, eliminating hot spots and preserving moisture. Holds at precise temperatures for hours without quality loss. 12 × 1/1 GN capacity, programmable cook and hold cycles.',
                'specs'             => ['Capacity' => '12 × 1/1 GN', 'Technology' => 'Halo Heat', 'Temp Range' => '60°C–200°C', 'Power' => '208–240V', 'Weight' => '95 kg'],
                'tags'              => ['cook hold', 'alto shaam', 'deal'],
            ],
            [
                'name'              => 'Blodgett DFG-100 Full-Size Gas Convection Oven',
                'sku'               => 'BLO-DFG100',
                'category_slug'     => 'convection-ovens',
                'brand_slug'        => 'blodgett',
                'price'             => 6800.00,
                'original_price'    => 9500.00,
                'is_featured'       => false,
                'sales_count'       => 290,
                'rating'            => 4.60,
                'review_count'      => 44,
                'short_description' => 'Full-size gas convection oven. 5 rack capacity, 60,000 BTU. Porcelain interior.',
                'description'       => 'The Blodgett DFG-100 delivers consistent baking and roasting results with its 60,000 BTU burner and dual blower convection system. Porcelain interior for easy cleaning, 5 stainless steel racks, and single door with cool-touch handle.',
                'specs'             => ['Burner' => '60,000 BTU', 'Rack Capacity' => '5', 'Interior' => 'Porcelain', 'Oven Temp' => 'Up to 260°C', 'Width' => '1067 mm'],
                'tags'              => ['convection oven', 'blodgett', 'bakery', 'deal'],
            ],
            [
                'name'              => 'Manitowoc ID-0502A Indigo NXT Ice Machine',
                'sku'               => 'MAN-ID0502A',
                'category_slug'     => 'ice-machines',
                'brand_slug'        => 'manitowoc',
                'price'             => 5900.00,
                'original_price'    => 7800.00,
                'is_featured'       => false,
                'sales_count'       => 350,
                'rating'            => 4.65,
                'review_count'      => 72,
                'short_description' => '230 kg/24h Indigo NXT cube ice maker. Air-cooled. Built-in LuminIce II hygiene.',
                'description'       => 'The Manitowoc Indigo NXT ID-0502A produces up to 230 kg of half-dice cube ice per 24 hours. LuminIce II built-in antimicrobial treatment, NXT IntelliCheck diagnostics, and integrated top-mount evaporator design for clean, efficient operation.',
                'specs'             => ['Ice Production' => '230 kg / 24h', 'Cube Type' => 'Half Dice', 'Cooling' => 'Air-cooled', 'Refrigerant' => 'R-404A', 'Width' => '762 mm'],
                'tags'              => ['ice machine', 'manitowoc', 'deal'],
            ],
            [
                'name'              => 'Middleby Marshall PS360 WB Pizza Oven',
                'sku'               => 'MM-PS360WB',
                'category_slug'     => 'commercial-electric-ovens',
                'brand_slug'        => 'middleby-marshall',
                'price'             => 14500.00,
                'original_price'    => 19000.00,
                'is_featured'       => false,
                'sales_count'       => 240,
                'rating'            => 4.80,
                'review_count'      => 48,
                'short_description' => 'WOW! Conveyor pizza oven, 12" belt, digital controls. Up to 120 pizzas/hour.',
                'description'       => 'The Middleby Marshall PS360 WB conveyor oven delivers consistent, high-volume pizza production at up to 120 pizzas per hour. 12-inch wide belt, Windata digital controls, variable speed, and patented air impingement technology.',
                'specs'             => ['Belt Width' => '305 mm', 'Conveyor Type' => 'Variable speed', 'Capacity' => 'Up to 120 pizzas/hr', 'Power' => '208–240V / 3-phase', 'Width' => '1626 mm'],
                'tags'              => ['pizza oven', 'middleby', 'conveyor', 'deal'],
            ],
            [
                'name'              => 'Hobart A200 20-Quart Planetary Mixer',
                'sku'               => 'HOB-A200',
                'category_slug'     => 'commercial-mixers',
                'brand_slug'        => 'hobart',
                'price'             => 8200.00,
                'original_price'    => 10500.00,
                'is_featured'       => false,
                'sales_count'       => 470,
                'rating'            => 4.85,
                'review_count'      => 93,
                'short_description' => '20-quart planetary mixer. 3 speeds, 1/3 HP motor. Bowl guard included.',
                'description'       => 'The Hobart A200 is the bakery and pastry standard. 19 L stainless bowl, 1/3 HP motor with 3-speed transmission, and includes wire whisk, flat beater, and dough hook. Bowls, attachments, and a full range of optional accessories available.',
                'specs'             => ['Bowl Capacity' => '19 L (20 qt)', 'Motor' => '1/3 HP', 'Speeds' => '3', 'Power' => '230V / 50Hz', 'Weight' => '64 kg'],
                'tags'              => ['mixer', 'hobart', 'bakery', 'deal'],
            ],
            [
                'name'              => 'Electrolux Professional 600 Induction Range',
                'sku'               => 'ELP-600IR-4',
                'category_slug'     => 'induction-cookers',
                'brand_slug'        => 'electrolux-professional',
                'price'             => 11500.00,
                'original_price'    => 15000.00,
                'is_featured'       => true,
                'sales_count'       => 320,
                'rating'            => 4.75,
                'review_count'      => 55,
                'short_description' => '4-zone induction range, 600 mm. 3.5 kW per zone. AISI 316 stainless worktop.',
                'description'       => 'The Electrolux Professional 600 4-zone induction range delivers precise power from 200 W to 3.5 kW per zone, 99-level settings, and an AISI 316 stainless steel worktop for maximum hygiene and durability. Silent operation, no open flame.',
                'specs'             => ['Zones' => '4', 'Power per Zone' => '3.5 kW', 'Total Power' => '14.0 kW', 'Worktop' => 'AISI 316', 'Width' => '600 mm'],
                'tags'              => ['induction', 'electrolux', 'deal'],
            ],

            // ─── FEATURED (is_featured = true, mix of categories) ────────────
            [
                'name'              => 'Turbochef Tornado 2 High-Speed Oven',
                'sku'               => 'TBC-TORN2',
                'category_slug'     => 'combi-ovens',
                'brand_slug'        => 'turbochef',
                'price'             => 24000.00,
                'original_price'    => 28500.00,
                'is_featured'       => true,
                'sales_count'       => 180,
                'rating'            => 4.85,
                'review_count'      => 34,
                'short_description' => 'High-speed oven cooks up to 15× faster. Countertop, no ventilation required.',
                'description'       => 'The Turbochef Tornado 2 uses Impingement, microwave, and convection to cook up to 15 times faster than conventional ovens. Vent-free operation, perfect for counter use in cafés, hotels, and quick-service restaurants. 0.6 kW footprint.',
                'specs'             => ['Cook Speed' => 'Up to 15× faster', 'Oven Temp' => 'Up to 232°C', 'Ventilation' => 'Catalytic converter, no hood needed', 'Power' => '230V / 50Hz', 'Width' => '597 mm'],
                'tags'              => ['high speed oven', 'turbochef', 'quick service'],
            ],
            [
                'name'              => 'Cleveland 24CEM8 Electric Tilt Skillet',
                'sku'               => 'CLV-24CEM8',
                'category_slug'     => 'commercial-electric-ovens',
                'brand_slug'        => 'cleveland-range',
                'price'             => 18000.00,
                'is_featured'       => true,
                'sales_count'       => 145,
                'rating'            => 4.70,
                'review_count'      => 27,
                'short_description' => '95 L electric tilt skillet, manual tilt, 16 kW. Stainless cover included.',
                'description'       => 'The Cleveland 24CEM8 tilt skillet handles braising, frying, simmering, and steaming in one unit. 95 L capacity, 16 kW heating element, manual gear-driven tilt with draw-off spigot, and a stainless steel hinged cover.',
                'specs'             => ['Capacity' => '95 L', 'Heating Element' => '16 kW', 'Tilt' => 'Manual gear-driven', 'Power' => '400V / 3N~', 'Width' => '1067 mm'],
                'tags'              => ['tilt skillet', 'cleveland', 'catering'],
            ],
            [
                'name'              => 'Faema E71 E Imperial 2-Group Espresso Machine',
                'sku'               => 'FAE-E71E-2G',
                'category_slug'     => 'commercial-coffee-machines',
                'brand_slug'        => 'faema',
                'price'             => 16500.00,
                'original_price'    => 19800.00,
                'is_featured'       => true,
                'sales_count'       => 195,
                'rating'            => 4.80,
                'review_count'      => 42,
                'short_description' => '2-group espresso machine with E-WORK boiler management. Temperature stability.',
                'description'       => 'The Faema E71 E Imperial is a professional espresso machine featuring the E-WORK multi-boiler system for precise group temperature stability, T3 technology, and digital pressure profiling. Designed for specialty coffee bars and boutique hotels.',
                'specs'             => ['Groups' => '2', 'Technology' => 'E-WORK Multi-boiler + T3', 'Boiler' => '11 L main + 2 × 0.35 L', 'Power' => '230V / 50Hz', 'Weight' => '56 kg'],
                'tags'              => ['espresso', 'faema', 'coffee', 'hotel'],
            ],
            [
                'name'              => 'Welbilt MercoMax Heated Display Cabinet',
                'sku'               => 'WLB-MMAX-3',
                'category_slug'     => 'heated-display-cabinets',
                'brand_slug'        => 'welbilt',
                'price'             => 5800.00,
                'original_price'    => 7200.00,
                'is_featured'       => true,
                'sales_count'       => 260,
                'rating'            => 4.60,
                'review_count'      => 38,
                'short_description' => '3-shelf heated display case, 950 W. Curved glass, interior LED lighting.',
                'description'       => 'The Welbilt MercoMax heated display cabinet keeps food at safe holding temperatures while showcasing it attractively. 3 adjustable stainless shelves, curved tempered glass, rear access, LED interior, and programmable digital temperature.',
                'specs'             => ['Shelves' => '3 adjustable', 'Power' => '950 W', 'Temperature' => '65°C–90°C', 'Glass' => 'Curved tempered', 'Width' => '750 mm'],
                'tags'              => ['heated display', 'welbilt', 'display'],
            ],
            [
                'name'              => 'Meiko M-iQ Pass-Through Dishwasher',
                'sku'               => 'MEI-MIQ-PT',
                'category_slug'     => 'commercial-dishwashers',
                'brand_slug'        => 'meiko',
                'price'             => 28000.00,
                'original_price'    => 34000.00,
                'is_featured'       => true,
                'sales_count'       => 175,
                'rating'            => 4.90,
                'review_count'      => 61,
                'short_description' => 'M-iQ intelligent dishwasher, 900 racks/hr. Heat pump, near-zero emissions.',
                'description'       => 'The Meiko M-iQ is the world\'s first dishwasher with an integrated heat pump. Rinse water heat is recovered with near-zero steam emission, reducing energy costs by up to 50%. Intelligent sensors automatically adjust cycle parameters.',
                'specs'             => ['Capacity' => '900 racks/hr', 'Technology' => 'Heat pump', 'Steam Emission' => 'Near-zero', 'Power' => '400V / 3N~', 'Width' => '1010 mm'],
                'tags'              => ['dishwasher', 'meiko', 'hotel', 'energy saving'],
            ],
            [
                'name'              => 'Carpigiani LB-502G Gelato Batch Freezer',
                'sku'               => 'CAR-LB502G',
                'category_slug'     => 'commercial-freezers',
                'brand_slug'        => 'carpigiani',
                'price'             => 35000.00,
                'is_featured'       => true,
                'is_new'            => true,
                'sales_count'       => 68,
                'rating'            => 4.95,
                'review_count'      => 14,
                'short_description' => '5 L gravity-fed gelato batch freezer. Stainless steel cylinder. 15 min cycle.',
                'description'       => 'The Carpigiani LB-502G produces up to 12 kg/hour of artisan gelato, sorbet, and frozen desserts. Gravity-fed system, 5 L stainless steel cylinder, refrigerated hopper, automatic extraction, and patented Mix & Match program.',
                'specs'             => ['Cylinder' => '5 L', 'Hopper' => 'Refrigerated 5 L', 'Output' => 'Up to 12 kg/hr', 'Cycle Time' => '~15 min', 'Width' => '530 mm'],
                'tags'              => ['gelato', 'carpigiani', 'ice cream', 'new'],
            ],
            [
                'name'              => 'Robot Coupe CL50D Vegetable Preparation Machine',
                'sku'               => 'RC-CL50D',
                'category_slug'     => 'vegetable-prep-machines',
                'brand_slug'        => 'robot-coupe',
                'price'             => 7600.00,
                'original_price'    => 9200.00,
                'is_featured'       => false,
                'sales_count'       => 385,
                'rating'            => 4.80,
                'review_count'      => 66,
                'short_description' => 'Continuous-feed vegetable cutter with 5 discs. 550 kg/hr throughput.',
                'description'       => 'The Robot Coupe CL50D is the standard for high-volume vegetable preparation. 0.75 kW motor, 5 double-sided discs (slice, grate, julienne, ripple, dice), continuous feed hopper, and 550 kg/hr throughput. Motor unit and hopper dishwasher safe.',
                'specs'             => ['Motor' => '0.75 kW', 'Throughput' => 'Up to 550 kg/hr', 'Discs Included' => '5', 'Power' => '230V / 50Hz', 'Weight' => '13 kg'],
                'tags'              => ['vegetable cutter', 'robot coupe', 'preparation'],
            ],
            [
                'name'              => 'Comenda AC2 Hood Dishwasher',
                'sku'               => 'COM-AC2',
                'category_slug'     => 'commercial-dishwashers',
                'brand_slug'        => 'comenda',
                'price'             => 12800.00,
                'original_price'    => 15500.00,
                'is_featured'       => false,
                'sales_count'       => 280,
                'rating'            => 4.65,
                'review_count'      => 47,
                'short_description' => 'Hood-type dishwasher, 480 racks/hr. Self-cleaning, rinse booster pump.',
                'description'       => 'The Comenda AC2 hood dishwasher features a powerful rinse booster pump, auto-clean cycle, and 480 racks/hr capacity. Stainless steel wash and rinse arms, electronic controls, and built-in rinse aid and detergent dispenser.',
                'specs'             => ['Capacity' => '480 racks/hr', 'Wash Temp' => '55°C', 'Rinse Temp' => '85°C', 'Booster Pump' => 'Yes', 'Width' => '660 mm'],
                'tags'              => ['dishwasher', 'comenda', 'warewashing'],
            ],
            [
                'name'              => 'Alto-Shaam CTP7-20H Combitherm CT PROformance',
                'sku'               => 'ALS-CTP720H',
                'category_slug'     => 'combi-ovens',
                'brand_slug'        => 'alto-shaam',
                'price'             => 42000.00,
                'is_featured'       => true,
                'is_new'            => true,
                'sales_count'       => 55,
                'rating'            => 4.90,
                'review_count'      => 11,
                'short_description' => '7 × 2/1 GN Combitherm combi oven. ChefLinc remote monitoring, Structured Steam.',
                'description'       => 'The Alto-Shaam Combitherm CT PROformance features patented Structured Steam and Combitherm Pure technology for superior moisture and cooking results. 7 × 2/1 GN, ChefLinc cloud monitoring, and Vector H technology for multi-zone cooking.',
                'specs'             => ['Capacity' => '7 × 2/1 GN', 'Technology' => 'Structured Steam + Vector H', 'Monitoring' => 'ChefLinc cloud', 'Power' => '400V / 3N~', 'Width' => '1076 mm'],
                'tags'              => ['combi oven', 'alto shaam', 'hotel', 'new'],
            ],
            [
                'name'              => 'True T-23 Undercounter Refrigerator',
                'sku'               => 'TRUE-T23UC',
                'category_slug'     => 'under-counter-refrigerators',
                'brand_slug'        => 'true-refrigeration',
                'price'             => 6500.00,
                'original_price'    => 8200.00,
                'is_featured'       => false,
                'sales_count'       => 490,
                'rating'            => 4.70,
                'review_count'      => 81,
                'short_description' => '23 cu. ft. undercounter refrigerator. 115V, R-290 refrigerant, LED interior.',
                'description'       => 'The True T-23 undercounter refrigerator fits standard 870 mm work table height. 23 cu. ft. capacity, 2 adjustable PVC shelves, LED interior, and R-290 eco-friendly refrigerant. Stainless steel exterior and interior.',
                'specs'             => ['Capacity' => '23 cu. ft.', 'Temp Range' => '0°C to +7°C', 'Refrigerant' => 'R-290', 'Shelves' => '2 adjustable', 'Width' => '1219 mm'],
                'tags'              => ['undercounter fridge', 'true', 'deal'],
            ],
            [
                'name'              => 'Cambro CBP1826V148 Full-Size Sheet Pan Rack',
                'sku'               => 'CAM-CBP1826',
                'category_slug'     => 'mobile-storage-racks',
                'brand_slug'        => 'cambro',
                'price'             => 950.00,
                'original_price'    => 1200.00,
                'is_featured'       => false,
                'sales_count'       => 820,
                'rating'            => 4.50,
                'review_count'      => 190,
                'short_description' => 'Full-size 20-shelf pan rack with cover. NSF, polypropylene, 4 swivel casters.',
                'description'       => 'The Cambro full-size sheet pan rack holds up to 20 full-size sheet pans or 40 half-size pans. All-polypropylene construction resists corrosion and odours, 4 swivel casters (2 with brakes), and available cover.',
                'specs'             => ['Capacity' => '20 full-size pans', 'Material' => 'Polypropylene', 'Casters' => '4 swivel (2 braked)', 'Height' => '1753 mm', 'Weight' => '11.8 kg'],
                'tags'              => ['pan rack', 'cambro', 'storage'],
            ],
        ];
    }
}
